### PR TITLE
Now Compatible with python 3.5

### PR DESCRIPTION
**Pull request by ovarene**
Handling AST NameConstant in matching and aggregation
Date parsing test error

### CODE REVIEW

**Comment by alonho** [comment]
Thanks for the PR. I think the code assumes dropping support for python 2.X.
Perhaps we can use six (a library) to maintain compatibility with 2 and 3.

**Comment by ovarene** [comment]
python2 is quite old ... dropping its support would be easier

anyway, the only thing not compatible with python2 is the print function
otherwise, it should work correctly

Olivier Varene

**Comment by cjmaynar** [comment]
In the 3 years since this was opened Python 2 usage has continued to drop. Any chance of merging this in at this point?

**Comment by cjmaynar** [comment]
Thanks for the merge! Can you also release a new pip package for this version as well?

**Comment by luiscastro193** [comment]
Yeah, a new pip package would be cool

**Pull request merged**
